[package]
name = "TransFEL"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
eframe = "0.36.1"
egui = "0.32"
rfd    = "0.15"   # selector de archivos nativo del PC

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

# El decodificado y el escalado tambien deben ir rapido en depuracion,
# o el video se ve a tirones mientras desarrollas.
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
